### ISSUE TITLE
Asking for header files

### ISSUE THREAD

**Issue by f-rank** [snowkit/linc_nanovg#3]
Does this need glew-2.0.0 as a dependency ?
I found what it is asking for in the GL directory of GLEW but it may be from some other place because it threw a lot of stuff out after it found the file.
Thanks.

**Comment by dazKind** [comment]
Yeah, it is included and initialized here: https://github.com/snowkit/linc_nanovg/blob/master/linc/linc_nanovg.cpp#L11

I think we forgot to point that dependency out. Although im not sure if it was an requirement for nanovg itself or if I included it to make it run outside of frameworks like snow.

**Comment by f-rank** [comment]
Thanks for confirming.
I am trying to run it outside of snow but having no luck finding out how to point it to another renderer, will try to follow through see if I get it running somehow. Looks great.

**Comment by dazKind** [comment]
Cool. All you need is a window with an ogl context and you can basically run the drawcmds.

**Comment by ruby0x1** [comment]
We can add a define to not use/initialize glew if it's being troublesome?

**Comment by f-rank** [comment]
Got past the glew stuff. Its the other issue that I added that is stomping me right now.
